application: chessboard-web
version: 2
runtime: python
api_version: 1

handlers:
- url: /
  static_files: board.html
  upload: board.html

- url: /(.*\.(html|css|js))
  static_files: \1
  upload: .*\.(html|css|js)

- url: /images
  static_dir: images

- url: /scripts
  static_dir: scripts
